/* Admin panel language: English or Azərbaycan dili. Add/edit translations here (English text = key). */
const AL=localStorage.getItem('tk_admin_lang')==='az'?'az':'en';
const AZ={
'Orders':'Sifarişlər',
'Customers':'Müştərilər',
'Discounts':'Endirimlər',
'New':'Yeni',
'Confirmed':'Təsdiqləndi',
'Delivered':'Çatdırıldı',
'Cancelled':'Ləğv edildi',
'Could not load orders: {e}':'Sifarişləri yükləmək mümkün olmadı: {e}',
'Orders from other devices need the online database (see README). Right now only orders made in this browser are shown.':'Digər cihazlardan gələn sifarişlər üçün onlayn baza lazımdır (README-yə baxın). Hazırda yalnız bu brauzerdəki sifarişlər göstərilir.',
'new orders':'yeni sifariş',
'in total':'cəmi',
'Search name or phone':'Ad və ya telefon axtar',
'All statuses':'Bütün statuslar',
'Refresh':'Yenilə',
'Sale savings':'Endirim qənaəti',
'Promo code':'Promo kod',
'Total':'Cəmi',
'No orders yet.':'Hələ sifariş yoxdur.',
'Delete this order?':'Bu sifariş silinsin?',
'registered customers':'qeydiyyatlı müştəri',
'Name':'Ad',
'Phone number':'Telefon nömrəsi',
'Registered':'Qeydiyyat',
'Spent':'Xərclənib',
'Last order':'Son sifariş',
'No customers yet.':'Hələ müştəri yoxdur.',
'Sale - % off products (automatic)':'Endirim - məhsullara % (avtomatik)',
'Promo code - % off the basket':'Promo kod - səbətə % endirim',
'Promo code - fixed ₼ off the basket':'Promo kod - səbətə sabit ₼ endirim',
'New discount':'Yeni endirim',
'Type':'Növ',
'Value (% or ₼)':'Dəyər (% və ya ₼)',
'Code (customer types it in the basket)':'Kod (müştəri səbətdə yazır)',
'Minimum order ₼':'Minimum sifariş ₼',
'From (optional)':'Başlanğıc (istəyə bağlı)',
'Until (optional)':'Son (istəyə bağlı)',
'Products (empty = all products; hold Ctrl/Cmd to pick several)':'Məhsullar (boş = bütün məhsullar; bir neçəsini seçmək üçün Ctrl/Cmd basılı saxlayın)',
'Add discount':'Endirim əlavə et',
'Sales show the old price crossed out on the website. Promo codes are typed by the customer in the basket.':'Endirimlərdə saytda köhnə qiymət üstündən xətt çəkilir. Promo kodları müştəri səbətdə yazır.',
'Code':'Kod',
'products':'məhsul',
'All products':'Bütün məhsullar',
'Active':'Aktiv',
'No discounts yet.':'Hələ endirim yoxdur.',
'Percent is too high.':'Faiz çox yüksəkdir.',
'Enter a code.':'Kod yazın.',
'This code already exists.':'Bu kod artıq mövcuddur.',
'Delete this discount?':'Bu endirim silinsin?',
'Admin login':'Admin girişi','Username':'İstifadəçi adı','Code':'Kod','Log in':'Daxil ol','← Back to website':'← Sayta qayıt','View website':'Sayta bax','Log out':'Çıxış',
'Products':'Məhsullar','Home page':'Ana səhifə','Albums':'Albomlar','Colors':'Rənglər','Contact':'Əlaqə','Texts':'Mətnlər','Data':'Məlumat','Language':'Dil',
'Wrong username or code.':'İstifadəçi adı və ya kod yanlışdır.',
'Search products':'Məhsul axtar','+ Add product':'+ Məhsul əlavə et','Low stock (5 or less)':'Az qalıb (5 və ya az)','Out of stock':'Stokda yoxdur',
'Change price or stock and it saves automatically. Yellow = low stock, red = out of stock (the website shows an "Out of stock" label).':'Qiyməti və ya stoku dəyişin, avtomatik yadda saxlanılır. Sarı = az qalıb, qırmızı = stokda yoxdur (saytda "Stokda yoxdur" yazısı görünür).',
'Price ₼':'Qiymət ₼','Stock':'Stok','Edit':'Redaktə','Delete':'Sil','Delete {name}?':'{name} silinsin?','Edit product':'Məhsula düzəliş','Add product':'Məhsul əlavə et',
'Brand':'Brend','Model':'Model','Shape (for the drawn picture)':'Forma (çəkilmiş şəkil üçün)','Color':'Rəng',
'Image URL (or put the file in images/products/ as product-ID.jpg)':'Şəkil linki (və ya faylı images/products/ qovluğuna product-ID.jpg adı ilə qoyun)',
'Or upload a photo':'Və ya şəkil yükləyin','Description (optional, shown in every language)':'Təsvir (istəyə bağlı, bütün dillərdə göstərilir)',
'Size':'Həcm','Shade':'Çalar','Origin':'Mənşə','Save':'Yadda saxla','Cancel':'Ləğv et',
'lipstick':'dodaq boyası','tube':'tüp','bottle':'şüşə','jar':'banka','perfume':'ətir','palette':'palitra','nail':'dırnaq lakı',
'New album':'Yeni albom','Name (English)':'Ad (İngiliscə)','Name (Azərbaycan dili)':'Ad (Azərbaycan dili)','Name (Русский)':'Ad (Rusca)','Name (Türkçe)':'Ad (Türkcə)','Add album':'Albom əlavə et',
'Each album can have its own <b>cover photo</b> (shown on the home page and the Albums page). Without one, the first product photo is used.':'Hər albomun öz <b>üz qabığı şəkli</b> ola bilər (ana səhifədə və Albomlar səhifəsində göstərilir). Şəkil olmasa, ilk məhsulun şəkli istifadə olunur.',
'{n} products · key: {key}':'{n} məhsul · açar: {key}','Upload cover':'Şəkil yüklə','Cover from link':'Linkdən şəkil','Remove cover':'Şəkli sil','Delete album':'Albomu sil',
'Cover saved ✓':'Şəkil yadda saxlanıldı ✓','Could not read this image.':'Bu şəkli oxumaq mümkün olmadı.',
'Image link (https://...) or file path in your repository (images/home/cover.jpg):':'Şəkil linki (https://...) və ya repozitoriyada fayl yolu (images/home/cover.jpg):',
'Delete this album? The products stay on the website.':'Bu albom silinsin? Məhsullar saytda qalır.',
'Home page video':'Ana səhifə videosu','YouTube link':'YouTube linki','Save video':'Videonu saxla','Publish your changes':'Dəyişiklikləri dərc edin',
'Changes are saved in <b>this browser</b>. To show them to all visitors: click <b>Download store.json</b>, then upload that file to the main folder of your GitHub repository (replace the old one).':'Dəyişikliklər <b>bu brauzerdə</b> saxlanılır. Onları bütün ziyarətçilərə göstərmək üçün: <b>store.json yüklə</b> düyməsini basın, sonra həmin faylı GitHub repozitoriyasının əsas qovluğuna yükləyin (köhnəsini əvəz edin).',
'Download store.json':'store.json yüklə','Import a store.json file':'store.json faylını idxal et','Reset to the 30 sample products':'30 nümunə məhsula qaytar','Imported.':'İdxal edildi.',
'This is not a valid store.json file.':'Bu düzgün store.json faylı deyil.','Remove all your changes and go back to the sample data?':'Bütün dəyişikliklər silinsin və nümunə məlumatlara qayıdılsın?',
'Browser storage':'Brauzer yaddaşı','{mb} MB of about 5 MB used ({p}%)':'Təxminən 5 MB-dan {mb} MB istifadə olunub ({p}%)','- almost full!':'- demək olar dolub!',
'Uploaded photos live inside your browser (about 5 MB available) and inside store.json. If it fills up, put the photo files in <b>images/home/</b> on GitHub and paste their path (for example <b>images/home/slide-1.jpg</b>) into the photo fields instead.':'Yüklənmiş şəkillər brauzerinizdə (təxminən 5 MB yer var) və store.json faylında saxlanılır. Yaddaş dolarsa, şəkil fayllarını GitHub-da <b>images/home/</b> qovluğuna qoyun və onların yolunu (məsələn, <b>images/home/slide-1.jpg</b>) şəkil xanalarına yapışdırın.',
'Saved ✓':'Yadda saxlanıldı ✓',
'Online database':'Onlayn baza','Online database is ON: every change is saved for all visitors on all devices.':'Onlayn baza AÇIQDIR: hər dəyişiklik bütün cihazlarda bütün ziyarətçilər üçün saxlanılır.',
'Online database is NOT set up. Changes stay only in this browser. Follow the README (Firebase) steps and fill js/config.js.':'Onlayn baza qurulmayıb. Dəyişikliklər yalnız bu brauzerdə qalır. README (Firebase) addımlarını edin və js/config.js faylını doldurun.',
'Saved online ✓':'Onlayn yadda saxlanıldı ✓','Could not save online: {e}':'Onlayn saxlamaq mümkün olmadı: {e}','Online login failed: {e}':'Onlayn giriş alınmadı: {e}',
'Online database: first save will upload your current data.':'Onlayn baza: ilk saxlama hazırkı məlumatları yükləyəcək.','Upload everything to the online database now':'Hər şeyi indi onlayn bazaya yüklə',
'Edit the home page below. Photos are saved instantly; texts and options are saved with this button.':'Ana səhifəni aşağıda redaktə edin. Şəkillər dərhal saxlanılır; mətnlər və seçimlər bu düymə ilə saxlanılır.',
'Preview website ↗':'Sayta bax ↗','Save home page':'Ana səhifəni saxla','Home page saved ✓':'Ana səhifə saxlanıldı ✓',
'Top section texts':'Yuxarı bölmənin mətnləri','Leave a field empty to use the default text. Write the text in each language.':'Standart mətn üçün xananı boş buraxın. Mətni hər dildə yazın.',
'Title ({l})':'Başlıq ({l})','Text under the title ({l})':'Başlığın altındakı mətn ({l})','Top section style':'Yuxarı bölmənin üslubu','Layout':'Düzülüş',
'Text on the left, photo slider on the right':'Mətn solda, şəkil slayderi sağda','Full-width photo slider behind the text':'Mətnin arxasında tam enli şəkil slayderi',
'Seconds per slide (2 to 15)':'Hər slayd üçün saniyə (2-15)','"Full-width" needs at least one slider photo below.':'"Tam enli" üçün aşağıda ən azı bir slayder şəkli lazımdır.',
'Home page slider photos':'Ana səhifə slayder şəkilləri',
'These photos slide automatically at the top of the home page. Use bright, vertical or square photos for the "split" layout and wide photos for "full-width".':'Bu şəkillər ana səhifənin yuxarısında avtomatik dəyişir. "Bölünmüş" düzülüş üçün parlaq, şaquli və ya kvadrat şəkillər, "tam enli" üçün geniş şəkillər istifadə edin.',
'Single top photo (used only when there are no slider photos)':'Tək yuxarı şəkil (yalnız slayder şəkli olmadıqda istifadə olunur)','Upload a photo':'Şəkil yükləyin',
'Use the drawn picture':'Çəkilmiş şəkildən istifadə et','Currently the drawn picture is used.':'Hazırda çəkilmiş şəkil istifadə olunur.','Photo gallery':'Şəkil qalereyası',
'A grid of store photos shown on the home page (click opens the photo large). Add your store, shelves, new arrivals...':'Ana səhifədə göstərilən mağaza şəkilləri (kliklə böyüdülür). Mağazanızı, rəfləri, yeni məhsulları əlavə edin...',
'Bottom banner photo':'Aşağı banner şəkli','Background photo of the "Visit us" banner at the bottom of the home page.':'Ana səhifənin altındakı "Bizə gəlin" bannerinin fon şəkli.',
'Remove (use the color)':'Sil (rəngdən istifadə et)','No photo - the banner uses the main colors.':'Şəkil yoxdur - banner əsas rənglərdən istifadə edir.',
'Brands bar':'Brendlər zolağı','Show the brands bar':'Brendlər zolağını göstər','Brands in the bar (separate with commas; empty = all brands of your products)':'Zolaqdakı brendlər (vergüllə ayırın; boş = məhsulların bütün brendləri)',
'Featured products':'Seçilmiş məhsullar','Tick the products to show in "Featured products". Tick none to let the website choose automatically.':'"Seçilmiş məhsullar" bölməsində göstəriləcək məhsulları seçin. Heç birini seçməsəniz, sayt avtomatik seçəcək.',
'Show or hide sections':'Bölmələri göstər və ya gizlət','Albums section':'Albomlar bölməsi','Store video':'Mağaza videosu','"Why us" cards':'"Niyə biz" kartları','Bottom call-to-action banner':'Aşağı çağırış bannerı',
'The words of every section title can be changed in the <b>Texts</b> tab.':'Hər bölmə başlığının sözlərini <b>Mətnlər</b> bölməsində dəyişə bilərsiniz.',
'No photo':'Şəkil yoxdur','Image link or file path':'Şəkil linki və ya fayl yolu','(uploaded photo)':'(yüklənmiş şəkil)','Replace with an upload':'Yükləmə ilə əvəz et',
'Caption ({l}) - optional':'Başlıq ({l}) - istəyə bağlı','↑ Move up':'↑ Yuxarı','↓ Move down':'↓ Aşağı','Remove':'Sil','No photos yet.':'Hələ şəkil yoxdur.','Add photos':'Şəkil əlavə et',
'Choose one or many photos at once. They are resized automatically.':'Bir və ya bir neçə şəkli birdən seçin. Onların ölçüsü avtomatik kiçildilir.','+ Add from a link / file path':'+ Linkdən / fayl yolundan əlavə et',
'Maximum {n} photos here.':'Burada maksimum {n} şəkil ola bilər.','{n} photo(s) added ✓':'{n} şəkil əlavə edildi ✓',
'Image link (https://...) or file path in your repository (images/home/photo.jpg):':'Şəkil linki (https://...) və ya repozitoriyada fayl yolu (images/home/photo.jpg):',
'Photo added ✓':'Şəkil əlavə edildi ✓','Photo replaced ✓':'Şəkil əvəz edildi ✓','Photo saved ✓':'Şəkil saxlanıldı ✓','Remove this photo?':'Bu şəkil silinsin?','Photo removed':'Şəkil silindi',
'Main color (buttons, prices)':'Əsas rəng (düymələr, qiymətlər)','Soft color (light accents)':'Yumşaq rəng (açıq vurğular)','Dark color (header, footer)':'Tünd rəng (yuxarı və aşağı hissə)',
'Second dark color (brands bar)':'İkinci tünd rəng (brendlər zolağı)','Home page glow':'Ana səhifənin parıltısı','Page background':'Səhifə fonu','Text color':'Mətn rəngi',
'Rose & plum':'Qızılgül və gavalı','Ocean':'Okean','Emerald':'Zümrüd','Black & gold':'Qara və qızıl',
'Website colors':'Saytın rəngləri','Pick a ready palette or choose each color yourself.':'Hazır palitra seçin və ya hər rəngi özünüz seçin.','Save colors':'Rəngləri saxla','Reset colors':'Rəngləri sıfırla',
'Back to default colors.':'Standart rənglərə qayıdıldı.','Saved ✓ Open the website to see the colors.':'Yadda saxlanıldı ✓ Rəngləri görmək üçün saytı açın.',
'Store name':'Mağazanın adı','Phone number':'Telefon nömrəsi','Address':'Ünvan','Google Maps link':'Google Maps linki',
'Map location (coordinates like 40.332061,49.780442, or a place name)':'Xəritə yeri (40.332061,49.780442 kimi koordinatlar və ya yer adı)','Instagram link':'Instagram linki','TikTok link':'TikTok linki',
'Contact information':'Əlaqə məlumatları','Leave a field empty to keep the current default.':'Hazırkı standart dəyər üçün xananı boş buraxın.','Save contact information':'Əlaqə məlumatlarını saxla',
'Saved ✓ Open the website to see the change.':'Yadda saxlanıldı ✓ Dəyişikliyi görmək üçün saytı açın.',
'Words on the website':'Saytdakı sözlər',
'Change any word or sentence in each language. The grey text is the current one. Leave a box empty to keep it. Product names and album names are changed in their own tabs.':'Hər dildə istənilən söz və ya cümləni dəyişin. Boz mətn hazırkı mətndir. Saxlamaq üçün xananı boş buraxın. Məhsul və albom adları öz bölmələrində dəyişdirilir.',
'Search a word':'Söz axtar','Save texts':'Mətnləri saxla','Reset all texts':'Bütün mətnləri sıfırla','Remove all your text changes?':'Bütün mətn dəyişiklikləri silinsin?'
};
const tr=(s,v)=>{let r=(AL==='az'&&AZ[s]!==undefined)?AZ[s]:s;if(v)for(const k in v)r=r.split('{'+k+'}').join(v[k]);return r;};
function setAL(l){localStorage.setItem('tk_admin_lang',l==='az'?'az':'en');location.reload();}
function alPicker(){
  const L2=[['en','English'],['az','Azərbaycan dili']],cur=L2.find(x=>x[0]===AL)||L2[0];
  return `<div class="lp"><button class="lpb" type="button" aria-label="${tr('Language')}" onclick="this.parentNode.classList.toggle('open')">${flagImg(cur[0])}<span>${cur[1]}</span><i>▾</i></button><ul class="lpl">${L2.map(l=>`<li><button type="button" class="${l[0]===AL?'on':''}" onclick="setAL('${l[0]}')">${flagImg(l[0])}<span>${l[1]}</span></button></li>`).join('')}</ul></div>`;
}
document.addEventListener('click',e=>{if(!e.target.closest('.lp'))document.querySelectorAll('.lp.open').forEach(x=>x.classList.remove('open'));});
function trStatic(){
  document.documentElement.lang=AL;
  document.querySelectorAll('[data-tr]').forEach(e=>e.textContent=tr(e.textContent.trim()));
  document.querySelectorAll('.alang').forEach(s=>{s.innerHTML=alPicker();});
}
